# Generated by Django 4.2.9 on 2024-05-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee',
        ),
    ]
